### ISSUE TITLE
Out dated content

### ISSUE THREAD

**Issue by yaacov** [MeirKriheli/debian.org.il#1]
Hi, great update 👍 

**Issue**:
The content about Debian Hebrew project [1] is outdated ( from ~2005 ) about 12 years ago.
It contains links to the alioth page, which is even more outdated, also abot 12 years old :-)

**Proposed fix**:
I thing the best solution is to remove the links to the alioth project main page [2] and to the tutorial [3].  

[1] http://debian.org.il/debian-hebrew/
[2] http://debian-hebrew.alioth.debian.org/
[3] http://debian-hebrew.alioth.debian.org/tut-1/index.html

**Comment by yaacov** [comment]
Found my old passwords, updated the wiki link, and removed the outdated stuff from the alioth page :-)
Now users will not get a 12 years old data when pressing the links ... but we do not need links to mostly empty project page.

**Comment by yaacov** [comment]
@MeirKriheli ping ^^

**Comment by MeirKriheli** [comment]
@yaacov Thanks.

I probably missed something. What do you mean?

**Comment by yaacov** [comment]
> I probably missed something. What do you mean?

in the page http://debian.org.il/debian-hebrew/
you have a dead link to http://debian-hebrew.alioth.debian.org/tut-1/index.html

**Comment by MeirKriheli** [comment]
@yaacov Thanks, changed the link to the wiki page.
